version: '3.4'

services:
  mkdocs:
    container_name: mkdocs
    image: gehorak/mkdocs
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./datadir:/mkdocs
    networks:
      - network
      
networks:
  network: {}